/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TCodeRouteImport } from './routes/t.$code'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events.$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TCodeQrRouteImport } from './routes/t.$code_.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeQrRoute = TCodeQrRouteImport.update({
  id: '/t/$code_/qr',
  path: '/t/$code/qr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/t/$code': typeof TCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t/$code/qr': typeof TCodeQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/t/$code': typeof TCodeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t/$code/qr': typeof TCodeQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/t/$code': typeof TCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/t/$code_/qr': typeof TCodeQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/t/$code'
    | '/admin/'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/t/$code/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/t/$code'
    | '/admin'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/t/$code/qr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/t/$code'
    | '/admin/'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/t/$code_/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TCodeRoute: typeof TCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TCodeQrRoute: typeof TCodeQrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code_/qr': {
      id: '/t/$code_/qr'
      path: '/t/$code/qr'
      fullPath: '/t/$code/qr'
      preLoaderRoute: typeof TCodeQrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TCodeRoute: TCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TCodeQrRoute: TCodeQrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
