/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MijnTicketRouteImport } from './routes/mijn-ticket'
import { Route as PlatformRouteRouteImport } from './routes/platform/route'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as WordOrganisatorRouteImport } from './routes/word-organisator'
import { Route as AanvraagAanvraagIdRouteImport } from './routes/aanvraag.$aanvraagId'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiCoverRouteImport } from './routes/api/cover'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as MijnTicketEventIdRouteImport } from './routes/mijn-ticket.$eventId'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ScanEventIdRouteImport } from './routes/scan.$eventId'
import { Route as TCodeRouteImport } from './routes/t.$code'
import { Route as UploadsBestandRouteImport } from './routes/uploads.$bestand'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events.index'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events.$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PlatformEventsIndexRouteImport } from './routes/platform/events.index'
import { Route as PlatformEventsEventIdRouteImport } from './routes/platform/events.$eventId'
import { Route as TCodeQrRouteImport } from './routes/t.$code_.qr'
import { Route as AdminEventsEventIdDashboardRouteImport } from './routes/admin/events.$eventId_.dashboard'
import { Route as AdminEventsEventIdDeurRouteImport } from './routes/admin/events.$eventId_.deur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MijnTicketRoute = MijnTicketRouteImport.update({
  id: '/mijn-ticket',
  path: '/mijn-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const WordOrganisatorRoute = WordOrganisatorRouteImport.update({
  id: '/word-organisator',
  path: '/word-organisator',
  getParentRoute: () => rootRouteImport,
} as any)
const AanvraagAanvraagIdRoute = AanvraagAanvraagIdRouteImport.update({
  id: '/aanvraag/$aanvraagId',
  path: '/aanvraag/$aanvraagId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiCoverRoute = ApiCoverRouteImport.update({
  id: '/api/cover',
  path: '/api/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MijnTicketEventIdRoute = MijnTicketEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => MijnTicketRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanEventIdRoute = ScanEventIdRouteImport.update({
  id: '/scan/$eventId',
  path: '/scan/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsBestandRoute = UploadsBestandRouteImport.update({
  id: '/uploads/$bestand',
  path: '/uploads/$bestand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformEventsIndexRoute = PlatformEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformEventsEventIdRoute = PlatformEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const TCodeQrRoute = TCodeQrRouteImport.update({
  id: '/t/$code_/qr',
  path: '/t/$code/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdDashboardRoute =
  AdminEventsEventIdDashboardRouteImport.update({
    id: '/events/$eventId_/dashboard',
    path: '/events/$eventId/dashboard',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminEventsEventIdDeurRoute = AdminEventsEventIdDeurRouteImport.update({
  id: '/events/$eventId_/deur',
  path: '/events/$eventId/deur',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/platform': typeof PlatformRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mijn-ticket': typeof MijnTicketRouteWithChildren
  '/profiel': typeof ProfielRoute
  '/word-organisator': typeof WordOrganisatorRoute
  '/aanvraag/$aanvraagId': typeof AanvraagAanvraagIdRoute
  '/api/cover': typeof ApiCoverRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/mijn-ticket/$eventId': typeof MijnTicketEventIdRoute
  '/s/$token': typeof STokenRoute
  '/scan/$eventId': typeof ScanEventIdRoute
  '/t/$code': typeof TCodeRoute
  '/uploads/$bestand': typeof UploadsBestandRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/platform/events/$eventId': typeof PlatformEventsEventIdRoute
  '/t/$code/qr': typeof TCodeQrRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/platform/events/': typeof PlatformEventsIndexRoute
  '/admin/events/$eventId/dashboard': typeof AdminEventsEventIdDashboardRoute
  '/admin/events/$eventId/deur': typeof AdminEventsEventIdDeurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mijn-ticket': typeof MijnTicketRouteWithChildren
  '/profiel': typeof ProfielRoute
  '/word-organisator': typeof WordOrganisatorRoute
  '/aanvraag/$aanvraagId': typeof AanvraagAanvraagIdRoute
  '/api/cover': typeof ApiCoverRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/mijn-ticket/$eventId': typeof MijnTicketEventIdRoute
  '/s/$token': typeof STokenRoute
  '/scan/$eventId': typeof ScanEventIdRoute
  '/t/$code': typeof TCodeRoute
  '/uploads/$bestand': typeof UploadsBestandRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/platform/events/$eventId': typeof PlatformEventsEventIdRoute
  '/t/$code/qr': typeof TCodeQrRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/platform/events': typeof PlatformEventsIndexRoute
  '/admin/events/$eventId/dashboard': typeof AdminEventsEventIdDashboardRoute
  '/admin/events/$eventId/deur': typeof AdminEventsEventIdDeurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/platform': typeof PlatformRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mijn-ticket': typeof MijnTicketRouteWithChildren
  '/profiel': typeof ProfielRoute
  '/word-organisator': typeof WordOrganisatorRoute
  '/aanvraag/$aanvraagId': typeof AanvraagAanvraagIdRoute
  '/api/cover': typeof ApiCoverRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/mijn-ticket/$eventId': typeof MijnTicketEventIdRoute
  '/s/$token': typeof STokenRoute
  '/scan/$eventId': typeof ScanEventIdRoute
  '/t/$code': typeof TCodeRoute
  '/uploads/$bestand': typeof UploadsBestandRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/platform/events/$eventId': typeof PlatformEventsEventIdRoute
  '/t/$code_/qr': typeof TCodeQrRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/platform/events/': typeof PlatformEventsIndexRoute
  '/admin/events/$eventId_/dashboard': typeof AdminEventsEventIdDashboardRoute
  '/admin/events/$eventId_/deur': typeof AdminEventsEventIdDeurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/platform'
    | '/login'
    | '/mijn-ticket'
    | '/profiel'
    | '/word-organisator'
    | '/aanvraag/$aanvraagId'
    | '/api/cover'
    | '/events/$eventId'
    | '/events/new'
    | '/mijn-ticket/$eventId'
    | '/s/$token'
    | '/scan/$eventId'
    | '/t/$code'
    | '/uploads/$bestand'
    | '/admin/'
    | '/events/'
    | '/platform/'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/platform/events/$eventId'
    | '/t/$code/qr'
    | '/admin/events/'
    | '/platform/events/'
    | '/admin/events/$eventId/dashboard'
    | '/admin/events/$eventId/deur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mijn-ticket'
    | '/profiel'
    | '/word-organisator'
    | '/aanvraag/$aanvraagId'
    | '/api/cover'
    | '/events/$eventId'
    | '/events/new'
    | '/mijn-ticket/$eventId'
    | '/s/$token'
    | '/scan/$eventId'
    | '/t/$code'
    | '/uploads/$bestand'
    | '/admin'
    | '/events'
    | '/platform'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/platform/events/$eventId'
    | '/t/$code/qr'
    | '/admin/events'
    | '/platform/events'
    | '/admin/events/$eventId/dashboard'
    | '/admin/events/$eventId/deur'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/platform'
    | '/login'
    | '/mijn-ticket'
    | '/profiel'
    | '/word-organisator'
    | '/aanvraag/$aanvraagId'
    | '/api/cover'
    | '/events/$eventId'
    | '/events/new'
    | '/mijn-ticket/$eventId'
    | '/s/$token'
    | '/scan/$eventId'
    | '/t/$code'
    | '/uploads/$bestand'
    | '/admin/'
    | '/events/'
    | '/platform/'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/platform/events/$eventId'
    | '/t/$code_/qr'
    | '/admin/events/'
    | '/platform/events/'
    | '/admin/events/$eventId_/dashboard'
    | '/admin/events/$eventId_/deur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  MijnTicketRoute: typeof MijnTicketRouteWithChildren
  ProfielRoute: typeof ProfielRoute
  WordOrganisatorRoute: typeof WordOrganisatorRoute
  AanvraagAanvraagIdRoute: typeof AanvraagAanvraagIdRoute
  ApiCoverRoute: typeof ApiCoverRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsNewRoute: typeof EventsNewRoute
  STokenRoute: typeof STokenRoute
  ScanEventIdRoute: typeof ScanEventIdRoute
  TCodeRoute: typeof TCodeRoute
  UploadsBestandRoute: typeof UploadsBestandRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TCodeQrRoute: typeof TCodeQrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mijn-ticket': {
      id: '/mijn-ticket'
      path: '/mijn-ticket'
      fullPath: '/mijn-ticket'
      preLoaderRoute: typeof MijnTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-organisator': {
      id: '/word-organisator'
      path: '/word-organisator'
      fullPath: '/word-organisator'
      preLoaderRoute: typeof WordOrganisatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanvraag/$aanvraagId': {
      id: '/aanvraag/$aanvraagId'
      path: '/aanvraag/$aanvraagId'
      fullPath: '/aanvraag/$aanvraagId'
      preLoaderRoute: typeof AanvraagAanvraagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/cover': {
      id: '/api/cover'
      path: '/api/cover'
      fullPath: '/api/cover'
      preLoaderRoute: typeof ApiCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mijn-ticket/$eventId': {
      id: '/mijn-ticket/$eventId'
      path: '/$eventId'
      fullPath: '/mijn-ticket/$eventId'
      preLoaderRoute: typeof MijnTicketEventIdRouteImport
      parentRoute: typeof MijnTicketRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$eventId': {
      id: '/scan/$eventId'
      path: '/scan/$eventId'
      fullPath: '/scan/$eventId'
      preLoaderRoute: typeof ScanEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$bestand': {
      id: '/uploads/$bestand'
      path: '/uploads/$bestand'
      fullPath: '/uploads/$bestand'
      preLoaderRoute: typeof UploadsBestandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/events/': {
      id: '/platform/events/'
      path: '/events'
      fullPath: '/platform/events/'
      preLoaderRoute: typeof PlatformEventsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/events/$eventId': {
      id: '/platform/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/platform/events/$eventId'
      preLoaderRoute: typeof PlatformEventsEventIdRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/t/$code_/qr': {
      id: '/t/$code_/qr'
      path: '/t/$code/qr'
      fullPath: '/t/$code/qr'
      preLoaderRoute: typeof TCodeQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId_/dashboard': {
      id: '/admin/events/$eventId_/dashboard'
      path: '/events/$eventId/dashboard'
      fullPath: '/admin/events/$eventId/dashboard'
      preLoaderRoute: typeof AdminEventsEventIdDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$eventId_/deur': {
      id: '/admin/events/$eventId_/deur'
      path: '/events/$eventId/deur'
      fullPath: '/admin/events/$eventId/deur'
      preLoaderRoute: typeof AdminEventsEventIdDeurRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsEventIdDashboardRoute: typeof AdminEventsEventIdDashboardRoute
  AdminEventsEventIdDeurRoute: typeof AdminEventsEventIdDeurRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsEventIdDashboardRoute: AdminEventsEventIdDashboardRoute,
  AdminEventsEventIdDeurRoute: AdminEventsEventIdDeurRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PlatformRouteRouteChildren {
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformEventsEventIdRoute: typeof PlatformEventsEventIdRoute
  PlatformEventsIndexRoute: typeof PlatformEventsIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformEventsEventIdRoute: PlatformEventsEventIdRoute,
  PlatformEventsIndexRoute: PlatformEventsIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

interface MijnTicketRouteChildren {
  MijnTicketEventIdRoute: typeof MijnTicketEventIdRoute
}

const MijnTicketRouteChildren: MijnTicketRouteChildren = {
  MijnTicketEventIdRoute: MijnTicketEventIdRoute,
}

const MijnTicketRouteWithChildren = MijnTicketRoute._addFileChildren(
  MijnTicketRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  MijnTicketRoute: MijnTicketRouteWithChildren,
  ProfielRoute: ProfielRoute,
  WordOrganisatorRoute: WordOrganisatorRoute,
  AanvraagAanvraagIdRoute: AanvraagAanvraagIdRoute,
  ApiCoverRoute: ApiCoverRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsNewRoute: EventsNewRoute,
  STokenRoute: STokenRoute,
  ScanEventIdRoute: ScanEventIdRoute,
  TCodeRoute: TCodeRoute,
  UploadsBestandRoute: UploadsBestandRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TCodeQrRoute: TCodeQrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
